baseURL = "https://blog.ojizero.tech"
languageCode = "en-us"
title = "ojizero/blog"
theme = "hello-friend"

[params]
  defaultTheme = "dark"
  showReadingTime = true

[languages]
  [languages.en.params.logo]
    logoText = 'ojizero/blog'

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/ojizero"
    weight = -110
