baseURL = "https://blog.ojizero.tech"
languageCode = "en-us"
title = "ojizero/blog"
theme = "hello-friend"

[params]
  defaultTheme = "dark"
  showReadingTime = true

[languages]
  [languages.en.params.logo]
    logoText = 'ojizero/blog'
